apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: example-role
rules:
  - apiGroups: [ "" ]
    resources: [ "*" ] # Noncompliant
    verbs: [ "get", "list" ]
