on:
  workflow_dispatch:
    inputs:
      #      short-description:
      #        description: 'A short description for the release ticket'
      #        required: true
      #        type: string
      branch:
        description: 'The branch from which to release.'
        required: false
        default: 'master'
        type: string

jobs:
  freeze-branch:
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
    steps:
      - uses: SonarSource/release-github-actions/lock-branch@v1
        with:
          branch: ${{ inputs.branch }}
          freeze: false
