name: Full release

on:
  workflow_dispatch:
    inputs:
      short-description:
        description: 'A short description for the release ticket'
        required: true
        type: string
      branch:
        description: 'The branch from which to release.'
        required: false
        default: 'master'
        type: string
      dry-run:
        description: 'Test mode: use Jira sandbox and create a draft GitHub release'
        required: false
        default: false
        type: boolean

jobs:
  release:
    name: Release
    uses: SonarSource/release-github-actions/.github/workflows/ide-automated-release.yml@6f94d0d49b2bb6d324f3110ef078e3a5bd95604e # 1.5.4
    permissions:
      statuses: read
      id-token: write
      contents: write
      actions: write
      pull-requests: write
    with:
      jira-project-key: "SLI"
      project-name: "SonarQube for IntelliJ"
      short-description: ${{ inputs.short-description }}
      branch: ${{ inputs.branch }}
      is-test-run: ${{ inputs.dry-run }}

  bump-version:
    name: Bump version
    needs:
      - release
    runs-on: github-ubuntu-latest-m
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: SonarSource/release-github-actions/bump-version@6f94d0d49b2bb6d324f3110ef078e3a5bd95604e # 1.5.4
        with:
          version: ${{ needs.release.outputs.new-version }}
          base-branch: ${{ inputs.branch }}
          token: ${{ github.token }}
