name: Notify Failure
on:
  workflow_run:
    workflows: [ "Build", "Plugin Verifier Nightly" ]
    types:
      - completed
    branches:
      - master

permissions:
  id-token: write

jobs:
  notify:
    runs-on: sonar-xs
    name: Send Slack Notification
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Vault Secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@c154b4a417b51cb98dd71137f49bf20e77c56820 # 3.4.0
        with:
          secrets: |
            development/kv/data/slack token | SLACK_BOT_TOKEN;

      - name: Slack Notification on Failure
        uses: slackapi/slack-github-action@03ea5433c137af7c0495bc0cad1af10403fc800c # v3.0.2
        with:
          method: chat.postMessage
          token: ${{ fromJSON(steps.secrets.outputs.vault).SLACK_BOT_TOKEN }}
          # Slack channel squad-devex-flow-interrupts
          payload: |
            channel: C0ADM04C59A
            text: "Workflow failed in ${{ github.repository }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":x: *Repository:* ${{ github.repository }}\n*Branch:* ${{ github.event.workflow_run.head_branch }}\n*Workflow:* ${{ github.event.workflow_run.name }}\n*Run:* <${{ github.event.workflow_run.html_url }}|#${{ github.event.workflow_run.run_number }}>"
