name: sonar-release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
      releaseId:
        type: string
        description: Release ID
        required: true
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@f8fc75de307f2547eec9bf9e2628bf67080a3414 # 6.8.1
    with:
      version: ${{ inputs.version }}
      releaseId: ${{ inputs.releaseId }}
      dryRun: ${{ inputs.dryRun }}
      slackChannel: C02E6L5C01H # squad-devex-private