name: Shadow scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'

jobs:
  scan:
    runs-on: github-ubuntu-latest-m
    name: Scan on shadow platforms
    permissions:
      id-token: write
      contents: write
    env:
      IDE_CACHE_DIR: /opt/jetbrains
      INTELLIJ_VERSION: "2023.1.7"
      CLION_VERSION: "2023.1.7"
      RIDER_VERSION: "2024.3.7"  # Rider 2023.3.6 disabled in Docker image
      RESHARPER_VERSION: "2024.3.7"
      ULTIMATE_VERSION: "2023.1.7"
    steps:
      - name: Vault
        id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/artifactory/token/SonarSource-sonarlint-intellij-private-reader access_token | ARTIFACTORY_ACCESS_TOKEN;

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.9.12

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::460386131003:role/deploymentroles/DevInfraSquadDockerImagesAccessRole
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Setup IDEs from Docker images
        uses: ./.github/actions/setup-ides
        with:
          ides: IC-${{ env.INTELLIJ_VERSION }} IU-${{ env.ULTIMATE_VERSION }} CL-${{ env.CLION_VERSION }} RS-${{ env.RESHARPER_VERSION }} RD-${{ env.RIDER_VERSION }}
          ide-cache-dir: ${{ env.IDE_CACHE_DIR }}

      - uses: SonarSource/ci-github-actions/build-gradle@v1
        env:
          ARTIFACTORY_ACCESS_USERNAME: vault-SonarSource-sonarlint-intellij-private-reader
          ARTIFACTORY_ACCESS_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_ACCESS_TOKEN }}
        with:
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          gradle-args: -x :its:check -x :buildPlugin -x :cyclonedxBom check jacocoTestReport

      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "org.sonarsource.sonarlint.intellij:sonarlint-intellij"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.sonarlint.intellij:sonarlint-intellij"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.sonarlint.intellij:sonarlint-intellij"
          shadow2_platform: "SQC-US"
